name: 'Anthropic Code Review'
description: 'Code review with claude.ai between to merge commits'
inputs:
  anthropic_api_key:
    required: true
    description: 'Anthropic API key'
  github_token:
    required: true
    description: 'Github Access Token'
runs:
  using: "composite"
  steps:
    - uses: anthropics/claude-code-action@beta
      env:
        github_token: ${{ inputs.github_token }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
