name: AI powered Code Review for PRs
on:
  workflow_call:
    secrets:
      anthropic_api_key:
        required: true
        description: 'Antropic API key'

jobs:
  ai-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
