name: CI Tests

on:
  workflow_call:
    inputs:
      mauticVersion:
        required: true
        type: string
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
        description: 'The GitHub runner to be used'
      pluginDir:
        required: true
        type: string
      additionalRequirements:
        required: false
        default: ''
        type: string
        description: 'Additional composer requirements'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
        description: 'The GitHub Personal Access Token'
      ANTHROPIC_API_KEY:
        required: false
        description: 'The API Key for Anthropics API'

jobs:
  determine-reqs:
    name: Determine requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this plugin
        uses: actions/checkout@v4
      - name: Check Test directory
        run: if [ -d ./Tests ]; then echo "PHPUNIT=1" >> $GITHUB_ENV; else echo "PHPUNIT=0" >> $GITHUB_ENV; fi
  ai-code-review:
    name: AI Code Review
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/ai_code_review.yaml@mtc-5990-ci-workflow
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  composer-install:
    name: Install composer dependencies
    needs: [determine-reqs]
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/composer-install.yaml@mtc-5990-ci-workflow
    with:
      mauticVersion: ${{ inputs.mauticVersion }}
      phpVersion: "8.3"
      pluginDir:  ${{ inputs.pluginDir }}
      additionalRequirements: ${{ inputs.additionalRequirements }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  no-db:
    name: Tests w/o DB
    needs: [composer-install]
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/no-db.yaml@mtc-5990-ci-workflow
    with:
      mauticVersion: ${{ inputs.mauticVersion }}
      phpVersion: "8.3"
      pluginDir:  ${{ inputs.pluginDir }}
      additionalRequirements: ${{ inputs.additionalRequirements }}
      composerCacheKey: ${{ needs.composer-install.outputs.composer-cache-key }}
      composerCacheDir: ${{ needs.composer-install.outputs.composer-cache-dir }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #integration-tests:
  #  name: Tests w/ DB
  #  needs: [composer-install]
  #  if: ${{ env.PHUNIT == 13 }}
  #  uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/phpunit.yaml@mtc-5990-ci-workflow
  #  with:
  #    mauticVersion: ${{ inputs.mauticVersion }}
  #    pluginDir:  ${{ inputs.pluginDir }}
  #    additionalRequirements: ${{ inputs.additionalRequirements }}
  #  secrets:
  #    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

