name: Mautic Plugin tests

on:
  workflow_call:
    inputs:
      mauticVersion:
        required: true
        type: string
      phpVersion:
        required: true
        type: string
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
        description: 'The GitHub runner to be used'
      pluginDir:
        required: true
        type: string
      additionalRequirements:
        required: false
        default: ''
        type: string
        description: 'Additional composer requirements'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
        description: 'The GitHub Personal Access Token'
    outputs:
      composer-cache-key:
        description: "The composer cache key"
        value: ${{ jobs.composer-install.outputs.composer-cache-key }}
      composer-cache-dir:
        description: "The composer cache dir"
        value: ${{ jobs.composer-install.outputs.composer-cache-dir }}

jobs:
  composer-install:
    name: Composer install
    runs-on: ubuntu-latest
    outputs:
      # Map the job outputs to step outputs
      composer-cache-key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}
      composer-cache-dir: ${{ steps.generate-composer-cache-dir.outputs.composer-cache-dir }}
    steps:
      - name: Checkout Mautic
        uses: actions/checkout@v4
        with:
          repository: mautic/mautic
          ref: ${{ inputs.mauticVersion }}

      - name: Checkout this plugin
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.pluginDir }}

      - name: Checkout required ci files
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Leuchtfeuer/mautic-ci-runner
          sparse-checkout: ciFiles
          path: ciFiles

      - name: Creates cache key depending on the composer files
        id: generate-composer-cache-key
        run: echo "composer-cache-key=composer-${{ hashFiles('composer.lock') }}-${{ inputs.phpVersion }}" >> "$GITHUB_OUTPUT"

      - name: Get Composer Cache Directory
        id: generate-composer-cache-dir
        run: echo "composer-cache-dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Restore Cache
        uses: actions/cache/restore@v4
        id: cache-restore-composer
        with:
          path: |
            bin
            vendor
          key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}

      - name: Setup PHP, with composer and extensions
        if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.phpVersion }}
          ini-values: -dpcov.enabled=0, pcov.directory=."
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
          coverage: pcov

      - name: Install Composer dependencies
        if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        run: composer install

      - name: Add plugin dependencies
        if: inputs.additionalRequirements != '' && steps.cache-restore-composer.outputs.cache-hit != 'true'
        run: composer require ${{ inputs.additionalRequirements }} --no-interaction

      - name: Create composer cache
        if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        id: cache-save-composer
        uses: actions/cache/save@v4
        with:
          path: |
            bin
            vendor
          key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}