name: CI

on:
  workflow_call:
    inputs:
      mauticVersion:
        required: false
        type: string
        description: "The Mautic MAJOR version"
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
        description: 'The GitHub runner to be used'
      pluginDir:
        required: false
        default: ''
        type: string
        description: 'NOT NEEDED; only here for compatibility'
      additionalRequirements:
        required: false
        default: ''
        type: string
        description: 'Additional composer requirements'
      skipRector:
        required: false
        type: boolean
        default: false
        description: "Should Rector be skipped?"
      skipCS:
        required: false
        type: boolean
        default: false
        description: "Should CSFixer be skipped?"
      skipPhpStan:
        required: false
        type: boolean
        default: false
        description: "Should PHPSTAN be skipped?"
      skipCodeReview:
        required: false
        type: boolean
        default: false
        description: "Should AI Code Review be skipped?"
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
        description: 'The GitHub Personal Access Token'
      ANTHROPIC_API_KEY:
        required: false
        description: 'The API Key for Anthropics API'

jobs:
  determine-reqs:
    name: Get requirements
    runs-on: ubuntu-latest
    outputs:
      UNIT: ${{ steps.directories.outputs.UNIT }}
      FUNCTIONAL: ${{ steps.directories.outputs.FUNCTIONAL }}
      mauticVersions: ${{ steps.mauticVersions.outputs.mauticVersions }}
      phpVersions: ${{ steps.mauticVersions.outputs.phpVersions }}
      pluginDir: ${{ steps.pluginDir.outputs.pluginDir }}
      CUSTOM_SETUP: ${{ steps.customSetupTests.outputs.CUSTOM_SETUP }}
      CUSTOM_TESTS: ${{ steps.customSetupTests.outputs.CUSTOM_TESTS }}
    steps:
      - name: Checkout this plugin
        uses: actions/checkout@v4
      - name: Checkout required ci files (1/2)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Leuchtfeuer/mautic-ci-runner
          sparse-checkout: globalSettings
          path: globalSettings
      - name: Checkout required ci files (2/2)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          sparse-checkout: |
            .github/custom_setup
            .github/custom_tests
          path: ciFiles
          ref: mtc-11409-custom-tests

      - name: Get Plugin Directory
        id: pluginDir
        run: |
          DIRECTORY=$(grep "install-directory-name" composer.json | cut -d'"' -f4)
          echo "pluginDir=$(echo 'plugins/'$DIRECTORY)" >> "$GITHUB_OUTPUT"
      - name: Check Test directory
        id: directories
        run: | 
          if [ -d ./Tests/Unit ]; then echo "UNIT=1" >> "$GITHUB_OUTPUT"; else echo "UNIT=0" >> "$GITHUB_OUTPUT"; fi
          if [ -d ./Tests/Functional ]; then echo "FUNCTIONAL=1" >> "$GITHUB_OUTPUT"; else echo "FUNCTIONAL=0" >> "$GITHUB_OUTPUT"; fi
      - name: Get Mautic Versions
        id: mauticVersions
        run: |
          mauticMajorVersion=$(echo -n '${{ github.event.pull_request.base.ref }}' | tail -c1 )
          echo "$mauticMajorVersion"
          echo "mauticVersions=$(grep $mauticMajorVersion globalSettings/globalSettings/versionRequirements.csv | cut -d';' -f2)" >> "$GITHUB_OUTPUT"
          echo "phpVersions=$(grep $mauticMajorVersion globalSettings/globalSettings/versionRequirements.csv | cut -d';' -f3)" >> "$GITHUB_OUTPUT"
      - name: Check for Custom Setup & Tests
        id: customSetupTests
        run: |
          if [ -n "$(find ciFiles/.github/custom_setup/*.sh -maxdepth 0)" ]; then echo "CUSTOM_SETUP=1" >> "$GITHUB_OUTPUT"; else echo "CUSTOM_SETUP=0" >> "$GITHUB_OUTPUT"; fi
          if [ -n "$(find ciFiles/.github/custom_tests/*.sh -maxdepth 0)" ]; then echo "CUSTOM_TESTS=1" >> "$GITHUB_OUTPUT"; else echo "CUSTOM_TESTS=0" >> "$GITHUB_OUTPUT"; fi

  check-dod:
    name: Check DoD
    needs: [ determine-reqs ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this plugin
        uses: actions/checkout@v4
      - name: Checkout required ci files
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Leuchtfeuer/mautic-ci-runner
          sparse-checkout: checkDod.sh
          path: checkDod
      - name: Run CheckDod
        run: bash checkDod/checkDod.sh

#  ai-code-review: #TODO: Re-activate (dev-only)
#    name: AI Code Review
#    if: ${{ inputs.skipCodeReview == false }}
#    needs: [ determine-reqs ]
#    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/ai_code_review.yaml@main
#    secrets:
#      PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  composer-install:
    name: Composer Install
    needs: [determine-reqs]
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/composer-install.yaml@main
    strategy:
      matrix:
        mauticVersion: ${{ fromJSON(needs.determine-reqs.outputs.mauticVersions) }}
        phpVersion: ${{ fromJSON(needs.determine-reqs.outputs.phpVersions) }}
    with:
      mauticVersion: ${{ matrix.mauticVersion }}
      phpVersion: ${{ matrix.phpVersion }}
      pluginDir:  ${{ needs.determine-reqs.outputs.pluginDir }}
      additionalRequirements: ${{ inputs.additionalRequirements }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  static-tests:
    name: Static Tests
    needs: [determine-reqs, composer-install]
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/static-tests.yaml@main
    strategy:
      matrix:
        mauticVersion: ${{ fromJSON(needs.determine-reqs.outputs.mauticVersions) }}
        phpVersion: ${{ fromJSON(needs.determine-reqs.outputs.phpVersions) }}
    with:
      mauticVersion: ${{ matrix.mauticVersion }}
      phpVersion: ${{ matrix.phpVersion }}
      pluginDir:  ${{ needs.determine-reqs.outputs.pluginDir }}
      additionalRequirements: ${{ inputs.additionalRequirements }}
      composerCacheKey: ${{ needs.composer-install.outputs.composer-cache-key }}
      skipRector: ${{ inputs.skipRector }}
      skipCS: ${{ inputs.skipCS }}
      skipPhpStan: ${{ inputs.skipPhpStan }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  unit-tests:
    name: Unit Tests
    needs: [determine-reqs,  composer-install ]
    if: ${{ needs.determine-reqs.outputs.UNIT == 1 }}
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/unit-tests.yaml@main
    strategy:
      matrix:
        mauticVersion: ${{ fromJSON(needs.determine-reqs.outputs.mauticVersions) }}
        phpVersion: ${{ fromJSON(needs.determine-reqs.outputs.phpVersions) }}
    with:
      mauticVersion: ${{ matrix.mauticVersion }}
      phpVersion: ${{ matrix.phpVersion }}
      pluginDir:  ${{ needs.determine-reqs.outputs.pluginDir }}
      additionalRequirements: ${{ inputs.additionalRequirements }}
      composerCacheKey: ${{ needs.composer-install.outputs.composer-cache-key }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  functional-tests:
    name: Functional Tests
    needs: [determine-reqs, composer-install]
    if: ${{ needs.determine-reqs.outputs.FUNCTIONAL == 1 }}
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/functional-tests.yaml@mtc-11409-custom-tests #TODO: Use correct ref (dev-only)
    strategy:
      matrix:
        mauticVersion: ${{ fromJSON(needs.determine-reqs.outputs.mauticVersions) }}
        phpVersion: ${{ fromJSON(needs.determine-reqs.outputs.phpVersions) }}
    with:
      mauticVersion: ${{ matrix.mauticVersion }}
      phpVersion: ${{ matrix.phpVersion }}
      pluginDir:  ${{ needs.determine-reqs.outputs.pluginDir }}
      additionalRequirements: ${{ inputs.additionalRequirements }}
      composerCacheKey: ${{ needs.composer-install.outputs.composer-cache-key }}
      customSetup: ${{ fromJSON(needs.determine-reqs.outputs.CUSTOM_SETUP) }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  custom-tests:
    name: Custom Tests
    needs: [ determine-reqs, composer-install ]
    if: ${{ needs.determine-reqs.outputs.CUSTOM_TESTS == 1 }}
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/custom-tests.yaml@mtc-11409-custom-tests #TODO: Use correct ref (dev-only)
    with:
      mauticVersion: ${{ matrix.mauticVersion }}
      phpVersion: ${{ matrix.phpVersion }}
      pluginDir: ${{ needs.determine-reqs.outputs.pluginDir }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

