name: Mautic Plugin tests without DB

on:
  workflow_call:
    inputs:
      mauticVersion:
        required: true
        type: string
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
        description: 'The GitHub runner to be used'
      pluginDir:
        required: true
        type: string
      additionalRequirements:
        required: false
        default: ''
        type: string
        description: 'Additional composer requirements'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
        description: 'The GitHub Personal Access Token'
      ANTHROPIC_API_KEY:
        required: false
        description: 'The API Key for Athropics API'

jobs:
  no-db:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.3' ]
        mautic-versions: [ '5.2.7' ]

    name: Tests on PHP ${{ matrix.php-versions }}, Mautic ${{ matrix.mautic-versions }}

    steps:
      - name: Checkout Mautic
        uses: actions/checkout@v4
        with:
          repository: mautic/mautic
          ref: ${{ matrix.mautic-versions }}

      - name: Checkout this plugin
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.pluginDir }}

      - name: Checkout required ci files
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Leuchtfeuer/mautic-ci-runner
          sparse-checkout: ciFiles
          path: ciFiles

      - name: DEBUG list
        run: ls -la

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: -dpcov.enabled=0, pcov.directory=."
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
          coverage: pcov

      - name: Add plugin dependencies
        if: inputs.additionalRequirements != ''
        run: composer require ${{ inputs.additionalRequirements }} --no-interaction --no-update

      - name: Creates cache key depending on the composer files
        id: generate-composer-cache-key
        run: echo "composer-cache-key=composer-${{ hashFiles('composer.lock') }}-${{ hashFiles('composer.patches.json') }}" >> "$GITHUB_OUTPUT"

      - name: Get Composer Cache Directory
        id: generate-composer-cache-dir
        run: echo "composer-cache-dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Restore Cache
        uses: actions/cache/restore@v4
        id: cache-restore-composer
        with:
          path: |
            bin
            vendor
          key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}

      - name: Install Composer dependencies
        #if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        run: composer install

      - name: Run Code Style check
        run: bin/php-cs-fixer fix ${{ inputs.pluginDir }} --config=.php-cs-fixer.php -v --dry-run --show-progress=dots --diff

      - name: PHPSTAN
        run: composer phpstan -- ${{ inputs.pluginDir }}

      - name: Rector
        run: composer rector -- --dry-run --no-progress-bar ${{ inputs.pluginDir }}

      - name: Twig Lint
        run: bin/console lint:twig ${{ inputs.pluginDir }}

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mautic-logs-php${{ matrix.php-versions }}-mautic${{ matrix.mautic-versions }}
          path: var/logs/

      - name: Create composer cache
        #if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        id: cache-save-composer
        uses: actions/cache/save@v4
        with:
          path: |
            bin
            vendor
          key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}