name: Mautic Plugin tests

on:
  workflow_call:
    inputs:
      mauticVersion:
        required: true
        type: string
      phpVersion:
        required: true
        type: string
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
        description: 'The GitHub runner to be used'
      pluginDir:
        required: true
        type: string
      additionalRequirements:
        required: false
        default: ''
        type: string
        description: 'Additional composer requirements'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
        description: 'The GitHub Personal Access Token'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ${{ inputs.phpVersion }}
        mautic-versions: ['5.2.7']

    name: Tests on PHP ${{ matrix.php-versions }}, ${{ matrix.db-types }}, Mautic ${{ matrix.mautic-versions }}

    steps:
      - name: Checkout Mautic
        uses: actions/checkout@v4
        with:
          repository: mautic/mautic
          ref: ${{ matrix.mautic-versions }}

      - name: Checkout this plugin
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.pluginDir }}

      - name: Checkout required ci files
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Leuchtfeuer/mautic-ci-runner
          sparse-checkout: ciFiles
          path: ciFiles

      - name: DEBUG list
        run: ls -la

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: -dpcov.enabled=0, pcov.directory=."
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
          coverage: pcov

      - name: Set SYMFONY_ENV to test
        run: |
          echo "SYMFONY_ENV=test" >> $GITHUB_ENV
          echo "MAUTIC_ENV=test" >> $GITHUB_ENV
          echo "MAUTIC_TABLE_PREFIX=mautic_" >> $GITHUB_ENV

      - name: Creates cache key depending on the composer files
        id: generate-composer-cache-key
        run: echo "composer-cache-key=composer-${{ hashFiles('composer.lock') }}" >> "$GITHUB_OUTPUT"

      - name: Get Composer Cache Directory
        id: generate-composer-cache-dir
        run: echo "composer-cache-dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Restore Cache
        uses: actions/cache/restore@v4
        id: cache-restore-composer
        with:
          path: |
            bin
            vendor
          key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}

      - name: Install Composer dependencies
        if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        run: composer install

      - name: Add plugin dependencies
        if: inputs.additionalRequirements != ''
        run: composer require ${{ inputs.additionalRequirements }} --no-interaction

      - name: Run PHPUNIT tests
        env:
          DB_PORT: ${{ job.services.database.ports[3306] }}
        run: XDEBUG_MODE=coverage APP_DEBUG=0 php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~tests|themes|vendor~" bin/phpunit -d memory_limit=1G --bootstrap vendor/autoload.php --configuration ${{ inputs.pluginDir }}/phpunit.xml --coverage-clover=${{ inputs.pluginDir }}/coverage.xml --coverage-text

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mautic-logs-php${{ matrix.php-versions }}-${{ matrix.db-types }}-mautic${{ matrix.mautic-versions }}
          path: var/logs/

      - name: Create composer cache
        if: steps.cache-restore-composer.outputs.cache-hit != 'true'
        id: cache-save-composer
        uses: actions/cache/save@v4
        with:
          path: |
            bin
            vendor
          key: ${{ steps.generate-composer-cache-key.outputs.composer-cache-key }}